{{- $fullName := include "team.fullname" . -}}
{{- $name := "operator" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
{{- if .Values.operator.image.pullSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ $name }}
  namespace: {{ .Values.serviceAccount.namespace }}
  labels:
    {{- include "team.labels" $data | nindent 4 }}
  {{- if .Values.operator.annotations }}
  annotations:
{{ toYaml .Values.operator.annotations | indent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}