---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: teams.ops.southbridge.io
spec:
  group: ops.southbridge.io
  names:
    kind: Team
    listKind: TeamList
    plural: teams
    singular: team
  scope: Cluster
  subresources:
    status: {}
  version: v1beta1
  versions:
    - name: v1beta1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            environments:
              type: array
  additionalPrinterColumns:
    - name: In charge
      type: string
      description: Person incharged for the team's environments
      JSONPath: .spec.inCharge
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
