{{- if .Values.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "team.serviceAccountName" .}}
  labels:
    {{- include "team.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "team.serviceAccountName" .}}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ include "team.serviceAccountName" .}}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}