---
apiVersion: ops.teams.io/v1
kind: Team
metadata:
  name: team
spec:
  inCharge: TeamFedorov
  environments:
    - name: developers
      maxPods: 30
      resources:
        limits:
          cpu: "5"
          memory: "5Gi"
        requests:
          cpu: "5"
          memory: "5Gi"
      podResources:
        limits:
          max:
            cpu: "1"
            memory: "1Gi"
          default:
            cpu: "100m"
            memory: "100Mi"
        requests:
          min:
            cpu: "50m"
            memory: "64Mi"
          default:
            cpu: "100m"
            memory: "100Mi"
        maxLimitRequestRatio:
          cpu: "2"