{{- if .Values.examplecrEnable.enabled -}}
apiVersion: ops.southbridge.io/v1beta1
kind: Team
metadata:
  name: {{ .Values.examplecrEnable.name }}
spec:
  {{- toYaml .Values.customResource | nindent 2 }}
{{- end }}
