---
apiVersion: ops.southbridge.io/v1beta1
kind: Team
metadata:
  name: team
spec:
  inCharge: POK8s
  environments:
    - name: developers
      maxPods: 30
      resources:
        limits:
          cpu: 2
          memory: 5Gi
        requests:
          cpu: 2
          memory: 5Gi
      podResources:
        limits:
          max:
            cpu: 1
            memory: 1Gi
          default:
            cpu: 100m
            memory: 100Mi
        requests:
          min:
            cpu: 50m
            memory: 64Mi
          default:
            cpu: 100m
            memory: 100Mi
        maxLimitRequestRatio:
          cpu: 2
          memory: 2
      tiller:
        enabled: false

    - name: qa
      resources:
        limits:
          cpu: 5
          memory: 5Gi
        requests:
          cpu: 5
          memory: 5Gi
      tiller:
        enabled: false

    - name: stage
      resources:
        limits:
          cpu: 2
          memory: 2Gi
        requests:
          cpu: 2
          memory: 2Gi
      tiller:
        enabled: false