apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: teams.ops.teams.io
  labels:
    app.kubernetes.io/name: team-operator
spec:
  group: ops.teams.io
  names:
    kind: Team
    listKind: TeamList
    plural: teams
    singular: team
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: In charge
          type: string
          description: Person incharged for the team's environments
          jsonPath: .spec.inCharge
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Max-Pods
          type: string
          jsonPath: .spec.environments.items.maxPods
        - name: CPU-Requests
          type: string
          jsonPath: .spec.environments.items.resources.requests.cpu
        - name: RAM-Requests
          type: string
          jsonPath: .spec.environments.items.resources.requests.memory
        - name: CPU-Limits
          type: string
          jsonPath: .spec.environments.items.resources.limits.cpu
        - name: RAM-Limits
          type: string
          jsonPath: .spec.environments.items.resources.limits.memory
      schema:
        openAPIV3Schema:
          type: object
          required:
            - kind
            - apiVersion
            - spec
          properties:
            kind:
              type: string
              enum:
                - Team
            apiVersion:
              type: string
              enum:
                - ops.teams.io/v1
            spec:
              type: object
              required:
                - inCharge
                - environments
              properties:
                inCharge:
                  type: string
                environments:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - maxPods
                      - resources
                      - podResources
                    properties:
                      name:
                        type: string
                        nullable: false
                      maxPods:
                        type: integer
                      resources:
                        type: object
                        required:
                          - limits
                          - requests
                        properties:
                          limits:
                            type: object
                            required:
                              - cpu
                              - memory
                            properties:
                              cpu:
                                type: string
                                pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                              memory:
                                type: string
                                pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                          requests:
                            type: object
                            required:
                              - cpu
                              - memory
                            properties:
                              cpu:
                                type: string
                                pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                              memory:
                                type: string
                                pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                      podResources:
                        type: object
                        required:
                          - limits
                          - requests
                          - maxLimitRequestRatio
                        properties:
                          limits:
                            type: object
                            required:
                              - max
                              - default
                            properties:
                              max:
                                type: object
                                required:
                                  - cpu
                                  - memory
                                properties:
                                  cpu:
                                    type: string
                                    pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                                  memory:
                                    type: string
                                    pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                              default:
                                type: object
                                required:
                                  - cpu
                                  - memory
                                properties:
                                  cpu:
                                    type: string
                                    pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                                  memory:
                                    type: string
                                    pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                          requests:
                            type: object
                            required:
                              - min
                              - default
                            properties:
                              min:
                                type: object
                                required:
                                  - cpu
                                  - memory
                                properties:
                                  cpu:
                                    type: string
                                    pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                                  memory:
                                    type: string
                                    pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                              default:
                                type: object
                                required:
                                  - cpu
                                  - memory
                                properties:
                                  cpu:
                                    type: string
                                    pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                                  memory:
                                    type: string
                                    pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                          maxLimitRequestRatio:
                            type: object
                            x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true